### ISSUE TITLE
Crashes Client on Forge 1.20.1

### ISSUE THREAD

**Issue by mimi-min** [mueseb/Carpet_Trapdoors-Forge#1]
The game crashes when I try to launch it with Carpet Trapdoors installed. I get the same result even if it's the only mod installed, with both versions marked for 1.20.1. 
 
 Unfortunately the logs aren't very helpful.

![image](https://github.com/mueseb/Carpet_Trapdoors-Forge/assets/29613956/8f62995a-7174-4aaf-a0f2-69525f86e04b)

https://pastebin.com/qmDciJVT

**Comment by mueseb** [comment]
It should be working now. Forge switched things up between versions 46 and 47. Give it a shot by downloading the latest Carpet Trapdoors version and let me know how if anything goes wrong.
